version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: book_ease_backend
    container_name: book_ease_backend_c1
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - DB_URL=mongodb+srv://Lava:Lava7259@cluster0.tg53wqj.mongodb.net/Book-Karo
      - JWT=book-karo-7619554450
      # - FRONTEND_URL=http://localhost:3000
      - TWILIO_ACCOUNT_SID=AC13293c9143ac243e5a173aff908c805d
      - TWILIO_AUTH_TOKEN=a369d6bcf58a002e47e99d0b58411072
      - Publishable_key=pk_test_51JMG5lSIAxlCeZwx3N3jTlrTYzbvQMesUcwJoGGOa4I8pFAUKZs0qdB9ONxO7gw17LPRNWBfN0cQ0vhxhk6DJPSA00PXrAY8qJ
      - Secret_key=sk_test_51JMG5lSIAxlCeZwxkHhJVtnFMY2wOswUa24IDJxfCHGY2TsyMfh2RHM1MqZiuD8owlK2rtey7gYkn6O7mpFnGKi000midnU9tc
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: book_ease_frontend
    container_name: book_ease_frontend_c1
    command: npm start
    env_file:
      - ./frontend/.env
    # environment:
    #   - REACT_APP_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true    

networks:
    app-network:
        driver: bridge
