version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: book_ease_backend
    container_name: book_ease_backend_c1
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: book_ease_frontend
    container_name: book_ease_frontend_c1
    command: npm start
    env_file:
      - ./frontend/.env
    # environment:
    #   - REACT_APP_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true    

networks:
    app-network:
        driver: bridge
